# Generated by Django 3.0 on 2022-06-12 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20220612_1209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
