# Generated by Django 3.0 on 2022-06-13 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0004_auto_20220613_2041'),
        ('profiles', '0002_auto_20220613_2042')
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
